/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'admin-invitations': AdminInvitation;
    media: Media;
    pages: Page;
    posts: Post;
    accounts: Account;
    sessions: Session;
    verifications: Verification;
    staffMembers: StaffMember;
    timeslots: Timeslot;
    'event-types': EventType;
    bookings: Booking;
    subscriptions: Subscription;
    plans: Plan;
    transactions: Transaction;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    timeslots: {
      bookings: 'bookings';
    };
    plans: {
      'event-typesPaymentMethods': 'event-types';
    };
    users: {
      timeslots: 'timeslots';
      account: 'accounts';
      session: 'sessions';
      userSubscription: 'subscriptions';
    };
  };
  collectionsSelect: {
    'admin-invitations': AdminInvitationsSelect<false> | AdminInvitationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    staffMembers: StaffMembersSelect<false> | StaffMembersSelect<true>;
    timeslots: TimeslotsSelect<false> | TimeslotsSelect<true>;
    'event-types': EventTypesSelect<false> | EventTypesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    scheduler: Scheduler;
  };
  globalsSelect: {
    scheduler: SchedulerSelect<false> | SchedulerSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      generateTimeslotsFromSchedule: TaskGenerateTimeslotsFromSchedule;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-invitations".
 */
export interface AdminInvitation {
  id: number;
  role: 'admin' | 'user';
  token: string;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            heading: string;
            subheading: string;
            backgroundImage: number | Media;
            ctaLink: string;
            ctaTitle: string;
            ctaDescription: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title: string;
            teamImage: number | Media;
            teamMembers?:
              | {
                  name: string;
                  image: number | Media;
                  bio: string;
                  id?: string | null;
                }[]
              | null;
            aboutTitle: string;
            aboutContent?:
              | {
                  paragraph: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            title: string;
            description: string;
            timeSlots?:
              | {
                  time: string;
                  monday?: string | null;
                  tuesday?: string | null;
                  wednesday?: string | null;
                  thursday?: string | null;
                  friday?: string | null;
                  saturday?: string | null;
                  sunday?: string | null;
                  id?: string | null;
                }[]
              | null;
            legend: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timetable';
          }
        | {
            title: string;
            description: string;
            videos?:
              | {
                  youtubeId: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title: string;
            description: string;
            pricingOptions?:
              | {
                  title: string;
                  price: string;
                  features?:
                    | {
                        feature: string;
                        id?: string | null;
                      }[]
                    | null;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            locationTitle: string;
            locationDescription: string;
            mapEmbedUrl: string;
            address: string;
            email: string;
            phone: string;
            form: number | Form;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            heroImage: number | Media;
            benefits?:
              | {
                  icon: number | Media;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            features?:
              | {
                  image: number | Media;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            cta: {
              title: string;
              description: string;
              form: number | Form;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'groups';
          }
        | {
            form: number | Form;
            enableIntro?: boolean | null;
            introContent?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'form-block';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt: string;
  heroImage?: (number | null) | Media;
  content: {
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
    blockName?: string | null;
    blockType: 'content';
  }[];
  publishedAt?: string | null;
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Accounts are used to store user accounts for authentication providers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  /**
   * The id of the account as provided by the SSO or equal to userId for credential accounts
   */
  accountId: string;
  /**
   * The id of the provider as provided by the SSO
   */
  providerId: string;
  /**
   * The user that the account belongs to
   */
  user: number | User;
  /**
   * The access token of the account. Returned by the provider
   */
  accessToken?: string | null;
  /**
   * The refresh token of the account. Returned by the provider
   */
  refreshToken?: string | null;
  /**
   * The id token for the account. Returned by the provider
   */
  idToken?: string | null;
  /**
   * The date and time when the access token will expire
   */
  accessTokenExpiresAt?: string | null;
  /**
   * The date and time when the refresh token will expire
   */
  refreshTokenExpiresAt?: string | null;
  /**
   * The scope of the account. Returned by the provider
   */
  scope?: string | null;
  /**
   * The hashed password of the account. Mainly used for email and password authentication
   */
  password?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  timeslots?: {
    docs?: (number | Timeslot)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Users chosen display name
   */
  name: string;
  /**
   * Whether the email of the user has been verified
   */
  emailVerified: boolean;
  /**
   * The image of the user
   */
  image?: string | null;
  createdAt: string;
  updatedAt: string;
  /**
   * The role/ roles of the user
   */
  role?: ('admin' | 'user')[] | null;
  /**
   * Whether the user is banned from the platform
   */
  banned?: boolean | null;
  /**
   * The reason for the ban
   */
  banReason?: string | null;
  /**
   * The date and time when the ban will expire
   */
  banExpires?: string | null;
  account?: {
    docs?: (number | Account)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  session?: {
    docs?: (number | Session)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  roles?: ('user' | 'admin')[] | null;
  stripeCustomerId?: string | null;
  stripeCustomers?:
    | {
        stripeAccountId: string;
        stripeCustomerId: string;
        id?: string | null;
      }[]
    | null;
  userSubscription?: {
    docs?: (number | Subscription)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * The email of the user
   */
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeslots".
 */
export interface Timeslot {
  id: number;
  date: string;
  startTime: string;
  endTime: string;
  /**
   * The time in minutes before the lesson will be closed for new bookings.
   */
  lockOutTime: number;
  originalLockOutTime?: number | null;
  location?: string | null;
  instructor?: (number | null) | StaffMember;
  eventType: number | EventType;
  /**
   * The number of places remaining
   */
  remainingCapacity?: number | null;
  bookings?: {
    docs?: (number | Booking)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Status of the lesson
   */
  bookingStatus?: string | null;
  /**
   * Whether the lesson is active and will be shown on the schedule
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staffMembers".
 */
export interface StaffMember {
  id: number;
  /**
   * The user associated with this instructor
   */
  user: number | User;
  name?: string | null;
  description?: string | null;
  /**
   * StaffMember profile image
   */
  profileImage?: (number | null) | Media;
  /**
   * Whether this instructor is active and can be assigned to timeslots
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types".
 */
export interface EventType {
  id: number;
  name: string;
  /**
   * How many people can book this class option?
   */
  places: number;
  description: string;
  paymentMethods?: {
    /**
     * Membership plans that grant access to this class option. Users with an active subscription to a selected plan can book without paying per session.
     */
    allowedPlans?: (number | Plan)[] | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  name: string;
  /**
   * Features that are included in this plan
   */
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Sessions included in this plan (e.g. 10 per month). Important: If a user has e.g. 10 bookings per month, they could book all 10 slots in a single lesson when allow multiple bookings per lesson is enabled.
   */
  sessionsInformation: {
    sessions?: number | null;
    intervalCount?: number | null;
    interval?: ('day' | 'week' | 'month' | 'quarter' | 'year') | null;
    /**
     * When enabled, subscribers can use multiple session credits on the same lesson (e.g. book 10 spots in one class if they have 10 sessions per month). When disabled, only one spot per lesson per user.
     */
    allowMultipleBookingsPerTimeslot: boolean;
  };
  stripeProductId?: string | null;
  /**
   * Price information for the plan
   */
  priceInformation?: {
    /**
     * Price of the plan
     */
    price?: number | null;
    /**
     * Number of intervals per period
     */
    intervalCount?: number | null;
    /**
     * How often the price is charged
     */
    interval?: ('day' | 'week' | 'month' | 'year') | null;
  };
  priceJSON?: string | null;
  /**
   * Status of the plan
   */
  status: 'active' | 'inactive';
  /**
   * Skip syncing to Stripe
   */
  skipSync?: boolean | null;
  'event-typesPaymentMethods'?: {
    docs?: (number | EventType)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  user: number | User;
  timeslot: number | Timeslot;
  status: 'pending' | 'confirmed' | 'cancelled' | 'waiting';
  /**
   * Payment transactions for this booking (Stripe, class pass, or subscription). Injected by @repo/bookings-payments when enabled.
   */
  transactions?: (number | Transaction)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Records how each booking was paid (Stripe, class pass, or subscription). Used to decrement class pass when paymentMethod is class_pass.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  /**
   * The booking this transaction applies to.
   */
  booking: number | Booking;
  /**
   * How the booking was paid.
   */
  paymentMethod: 'stripe' | 'class_pass' | 'subscription';
  /**
   * The class pass id used when paymentMethod is class_pass.
   */
  classPassId?: number | null;
  /**
   * Stripe payment intent id when paymentMethod is stripe.
   */
  stripePaymentIntentId?: string | null;
  /**
   * Subscription id when paymentMethod is subscription (booking created by subscription).
   */
  subscriptionId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sessions are active sessions for users. They are used to authenticate users with a session token
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  /**
   * The date and time when the session will expire
   */
  expiresAt: string;
  /**
   * The unique session token
   */
  token: string;
  createdAt: string;
  updatedAt: string;
  /**
   * The IP address of the device
   */
  ipAddress?: string | null;
  /**
   * The user agent information of the device
   */
  userAgent?: string | null;
  /**
   * The user that the session belongs to
   */
  user: number | User;
  /**
   * The admin who is impersonating this session
   */
  impersonatedBy?: (number | null) | User;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  user: number | User;
  plan: number | Plan;
  status: 'incomplete' | 'incomplete_expired' | 'trialing' | 'active' | 'past_due' | 'canceled' | 'unpaid' | 'paused';
  startDate?: string | null;
  endDate?: string | null;
  cancelAt?: string | null;
  stripeSubscriptionId?: string | null;
  /**
   * Skip syncing to Stripe
   */
  skipSync?: boolean | null;
  /**
   * Last confirmed booking date. Automatically updated when bookings are confirmed.
   */
  lastCheckIn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Verifications are used to verify authentication requests
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: number;
  /**
   * The identifier of the verification request
   */
  identifier: string;
  /**
   * The value to be verified
   */
  value: string;
  /**
   * The date and time when the verification request will expire
   */
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'generateTimeslotsFromSchedule';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'generateTimeslotsFromSchedule') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admin-invitations';
        value: number | AdminInvitation;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'verifications';
        value: number | Verification;
      } | null)
    | ({
        relationTo: 'staffMembers';
        value: number | StaffMember;
      } | null)
    | ({
        relationTo: 'timeslots';
        value: number | Timeslot;
      } | null)
    | ({
        relationTo: 'event-types';
        value: number | EventType;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-invitations_select".
 */
export interface AdminInvitationsSelect<T extends boolean = true> {
  role?: T;
  token?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              ctaLink?: T;
              ctaTitle?: T;
              ctaDescription?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              title?: T;
              teamImage?: T;
              teamMembers?:
                | T
                | {
                    name?: T;
                    image?: T;
                    bio?: T;
                    id?: T;
                  };
              aboutTitle?: T;
              aboutContent?:
                | T
                | {
                    paragraph?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timetable?:
          | T
          | {
              title?: T;
              description?: T;
              timeSlots?:
                | T
                | {
                    time?: T;
                    monday?: T;
                    tuesday?: T;
                    wednesday?: T;
                    thursday?: T;
                    friday?: T;
                    saturday?: T;
                    sunday?: T;
                    id?: T;
                  };
              legend?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              description?: T;
              videos?:
                | T
                | {
                    youtubeId?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              title?: T;
              description?: T;
              pricingOptions?:
                | T
                | {
                    title?: T;
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              locationTitle?: T;
              locationDescription?: T;
              mapEmbedUrl?: T;
              address?: T;
              email?: T;
              phone?: T;
              form?: T;
              id?: T;
              blockName?: T;
            };
        groups?:
          | T
          | {
              heroImage?: T;
              benefits?:
                | T
                | {
                    icon?: T;
                    text?: T;
                    id?: T;
                  };
              features?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    title?: T;
                    description?: T;
                    form?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'form-block'?:
          | T
          | {
              form?: T;
              enableIntro?: T;
              introContent?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  heroImage?: T;
  content?:
    | T
    | {
        content?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  publishedAt?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  accountId?: T;
  providerId?: T;
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  idToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  expiresAt?: T;
  token?: T;
  createdAt?: T;
  updatedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  user?: T;
  impersonatedBy?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staffMembers_select".
 */
export interface StaffMembersSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  description?: T;
  profileImage?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeslots_select".
 */
export interface TimeslotsSelect<T extends boolean = true> {
  date?: T;
  startTime?: T;
  endTime?: T;
  lockOutTime?: T;
  originalLockOutTime?: T;
  location?: T;
  instructor?: T;
  eventType?: T;
  remainingCapacity?: T;
  bookings?: T;
  bookingStatus?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types_select".
 */
export interface EventTypesSelect<T extends boolean = true> {
  name?: T;
  places?: T;
  description?: T;
  paymentMethods?:
    | T
    | {
        allowedPlans?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  user?: T;
  timeslot?: T;
  status?: T;
  transactions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  user?: T;
  plan?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  cancelAt?: T;
  stripeSubscriptionId?: T;
  skipSync?: T;
  lastCheckIn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  sessionsInformation?:
    | T
    | {
        sessions?: T;
        intervalCount?: T;
        interval?: T;
        allowMultipleBookingsPerTimeslot?: T;
      };
  stripeProductId?: T;
  priceInformation?:
    | T
    | {
        price?: T;
        intervalCount?: T;
        interval?: T;
      };
  priceJSON?: T;
  status?: T;
  skipSync?: T;
  'event-typesPaymentMethods'?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  booking?: T;
  paymentMethod?: T;
  classPassId?: T;
  stripePaymentIntentId?: T;
  subscriptionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  timeslots?: T;
  name?: T;
  emailVerified?: T;
  image?: T;
  createdAt?: T;
  updatedAt?: T;
  role?: T;
  banned?: T;
  banReason?: T;
  banExpires?: T;
  account?: T;
  session?: T;
  roles?: T;
  stripeCustomerId?: T;
  stripeCustomers?:
    | T
    | {
        stripeAccountId?: T;
        stripeCustomerId?: T;
        id?: T;
      };
  userSubscription?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Create recurring timeslots across your weekly schedule
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scheduler".
 */
export interface Scheduler {
  id: number;
  /**
   * When this schedule becomes active
   */
  startDate: string;
  /**
   * When this schedule stops generating timeslots
   */
  endDate: string;
  /**
   * Minutes before start time when booking closes (can be overridden per slot)
   */
  lockOutTime: number;
  /**
   * Default class type to use when creating timeslots (can be overridden per slot)
   */
  defaultEventType: number | EventType;
  /**
   * The days of the week and their time slots
   */
  week?: {
    days?:
      | {
          timeSlot?:
            | {
                startTime: string;
                endTime: string;
                /**
                 * Overrides the default class option
                 */
                eventType?: (number | null) | EventType;
                location?: string | null;
                instructor?: (number | null) | StaffMember;
                /**
                 * Overrides the default lock out time
                 */
                lockOutTime?: number | null;
                /**
                 * Whether the time slot is active and will be shown on the schedule
                 */
                active?: boolean | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Clear existing timeslots before generating new ones (this will not delete timeslots that have any bookings)
   */
  clearExisting?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scheduler_select".
 */
export interface SchedulerSelect<T extends boolean = true> {
  startDate?: T;
  endDate?: T;
  lockOutTime?: T;
  defaultEventType?: T;
  week?:
    | T
    | {
        days?:
          | T
          | {
              timeSlot?:
                | T
                | {
                    startTime?: T;
                    endTime?: T;
                    eventType?: T;
                    location?: T;
                    instructor?: T;
                    lockOutTime?: T;
                    active?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  clearExisting?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateTimeslotsFromSchedule".
 */
export interface TaskGenerateTimeslotsFromSchedule {
  input: {
    startDate: string;
    endDate: string;
    week: {
      days: {
        timeSlot: {
          startTime: string;
          endTime: string;
          eventType?: (number | null) | EventType;
          location?: string | null;
          instructor?: (number | null) | StaffMember;
          lockOutTime?: number | null;
        }[];
      }[];
    };
    clearExisting: boolean;
    defaultEventType: number | EventType;
    lockOutTime: number;
  };
  output: {
    success?: boolean | null;
    message?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}