name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "brugrappling" # Ensure this is a valid string
          POSTGRES_DB: bookings   # Set the name of the database to create
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Specify the Node.js version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Postgres is unavailable - sleeping"
            sleep 5
          done
          echo "Postgres is up!"

      - name: Set up Environment Variables
        run: |
          echo "DATABASE_URI=postgres://postgres:brugrappling@localhost:5432/bookings" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=brugrappling" >> $GITHUB_ENV # Ensure the password is set as an environment variable

      - name: Run tests
        env:
          DATABASE_URI: ${{ env.DATABASE_URI }} # Pass the DATABASE_URI to the test environment
        run: pnpm test

      - name: Build the project
        run: pnpm run build
