name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Add this section to define environment variables
      DATABASE_URI: postgres://postgres:brugrappling@localhost:5432/bookings # Ensure this matches your config
      STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
      PAYLOAD_SECRET: "sample-secret"

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: brugrappling # Consider using a secret for sensitive data
          POSTGRES_DB: bookings
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Postgres is unavailable - sleeping"
            sleep 5
          done
          echo "Postgres is up!"

      - name: Run database migrations
        run: pnpm run payload -- migrate

      - name: Debug Database URI
        run: echo "DATABASE_URI is set to ${{ env.DATABASE_URI }}"

      - name: Run tests
        run: pnpm test

      - name: Build the project
        run: pnpm run build
